from PySide6.QtCore import QLocale


LANG_SYSTEM = "system"
LANG_EN = "en"
LANG_JA = "ja"
LANG_VI = "vi"


def build_strings(min_reliable_chunk_size_mb):
    return {
        LANG_EN: {
            "menu_button": "Options",
            "menu_theme": "Theme",
            "menu_language": "Language",
            "menu_support_feedback": "Support & Feedback",
            "menu_how_to_use": "How to Use",
            "menu_setup_ffmpeg": "Setup ffmpeg",
            "menu_common_issues": "Common Issues",
            "menu_licenses": "Third-Party Licenses",
            "menu_about": "About MediaSeg",
            "theme_system": "System",
            "theme_dark": "Dark",
            "theme_light": "Light",
            "theme_neon": "Neon Tokyo",
            "lang_system": "System",
            "lang_english": "English",
            "lang_japanese": "Japanese",
            "lang_vietnamese": "Vietnamese",
            "drop_title": "Drop file to segment",
            "drop_subtitle": "Official: MP4, WEBM, MOV | Experimental: M4A, MP3, WAV",
            "path_placeholder": "Or select path manually...",
            "browse": "Browse",
            "config_title": "CONFIGURATION",
            "chunk_size": "Target Chunk Size",
            "output_folder": "Output Folder",
            "output_folder_help": "Use Browse to choose a custom output folder.",
            "output_folder_placeholder": "Same folder as source (Default). Use Browse to change.",
            "reset": "Reset",
            "start_idle": "\u00A0\u00A0Start Splitting",
            "start_preparing": "\u00A0\u00A0Preparing...",
            "start_converting": "\u00A0\u00A0Converting...",
            "start_splitting": "\u00A0\u00A0Splitting...",
            "start_cleaning": "\u00A0\u00A0Cleaning...",
            "start_completed": "\u00A0\u00A0Completed",
            "start_error": "\u00A0\u00A0Error",
            "open_output": "\u00A0\u00A0Open Output Folder",
            "fileinfo_empty": "No file selected",
            "fileinfo_format": "Format",
            "fileinfo_size": "Original Size",
            "fileinfo_duration": "Duration",
            "fileinfo_chunks": "Estimated Chunks",
            "size_warning_below_reliable": f"Below {min_reliable_chunk_size_mb} MB, some media files may fail.",
            "overlay_preparing_title": "Preparing",
            "overlay_preparing_body": "MediaSeg is preparing the current file. Controls are temporarily locked.",
            "overlay_converting_title": "Converting",
            "overlay_converting_body": "MediaSeg is converting this file before splitting. Controls are temporarily locked.",
            "overlay_splitting_title": "Splitting",
            "overlay_splitting_body": "MediaSeg is splitting the current file. Controls are temporarily locked.",
            "overlay_cleaning_title": "Cleaning",
            "overlay_cleaning_body": "MediaSeg is cleaning temporary files. Controls are temporarily locked.",
        },
        LANG_JA: {
            "menu_button": "オプション",
            "menu_theme": "テーマ",
            "menu_language": "言語",
            "menu_support_feedback": "サポートとフィードバック",
            "menu_how_to_use": "使い方",
            "menu_setup_ffmpeg": "ffmpeg設定",
            "menu_common_issues": "よくある問題",
            "menu_licenses": "サードパーティライセンス",
            "menu_about": "MediaSegについて",
            "theme_system": "システム",
            "theme_dark": "ダーク",
            "theme_light": "ライト",
            "theme_neon": "Neon Tokyo",
            "lang_system": "システム",
            "lang_english": "英語",
            "lang_japanese": "日本語",
            "lang_vietnamese": "ベトナム語",
            "drop_title": "ファイルをドロップして分割",
            "drop_subtitle": "正式: MP4, WEBM, MOV | 試験対応: M4A, MP3, WAV",
            "path_placeholder": "またはパスを手入力...",
            "browse": "参照",
            "config_title": "設定",
            "chunk_size": "目標チャンクサイズ",
            "output_folder": "出力フォルダ",
            "output_folder_help": "カスタム出力先は参照から選択してください。",
            "output_folder_placeholder": "既定ではソースと同じ場所に出力します。変更は参照から行います。",
            "reset": "リセット",
            "start_idle": "\u00A0\u00A0分割開始",
            "start_preparing": "\u00A0\u00A0準備中...",
            "start_converting": "\u00A0\u00A0変換中...",
            "start_splitting": "\u00A0\u00A0分割中...",
            "start_cleaning": "\u00A0\u00A0整理中...",
            "start_completed": "\u00A0\u00A0完了",
            "start_error": "\u00A0\u00A0エラー",
            "open_output": "\u00A0\u00A0出力フォルダを開く",
            "fileinfo_empty": "ファイル未選択",
            "fileinfo_format": "形式",
            "fileinfo_size": "元サイズ",
            "fileinfo_duration": "長さ",
            "fileinfo_chunks": "想定チャンク数",
            "size_warning_below_reliable": f"{min_reliable_chunk_size_mb} MB未満では、一部メディアで失敗する場合があります。",
            "overlay_preparing_title": "準備中",
            "overlay_preparing_body": "MediaSeg が現在のファイルを準備中です。操作は一時的にロックされています。",
            "overlay_converting_title": "変換中",
            "overlay_converting_body": "MediaSeg が分割前の変換を実行しています。操作は一時的にロックされています。",
            "overlay_splitting_title": "分割中",
            "overlay_splitting_body": "MediaSeg が現在のファイルを分割中です。操作は一時的にロックされています。",
            "overlay_cleaning_title": "整理中",
            "overlay_cleaning_body": "MediaSeg が一時ファイルを整理中です。操作は一時的にロックされています。",
        },
        LANG_VI: {
            "menu_button": "Tùy chọn",
            "menu_theme": "Giao diện",
            "menu_language": "Ngôn ngữ",
            "menu_support_feedback": "Hỗ trợ & Phản hồi",
            "menu_how_to_use": "Hướng dẫn sử dụng",
            "menu_setup_ffmpeg": "Thiết lập ffmpeg",
            "menu_common_issues": "Sự cố thường gặp",
            "menu_licenses": "Giấy phép bên thứ ba",
            "menu_about": "Giới thiệu MediaSeg",
            "theme_system": "Hệ thống",
            "theme_dark": "Tối",
            "theme_light": "Sáng",
            "theme_neon": "Neon Tokyo",
            "lang_system": "Hệ thống",
            "lang_english": "Tiếng Anh",
            "lang_japanese": "Tiếng Nhật",
            "lang_vietnamese": "Tiếng Việt",
            "drop_title": "Thả tệp vào đây để chia nhỏ",
            "drop_subtitle": "Chính thức: MP4, WEBM, MOV | Thử nghiệm: M4A, MP3, WAV",
            "path_placeholder": "Hoặc chọn đường dẫn...",
            "browse": "Duyệt...",
            "config_title": "CẤU HÌNH",
            "chunk_size": "Kích thước mỗi phần",
            "output_folder": "Thư mục đầu ra",
            "output_folder_help": "Nhấn \"Duyệt...\" để chọn thư mục đầu ra.",
            "output_folder_placeholder": "Mặc định sẽ lưu cùng thư mục với tệp gốc. Nhấn \"Duyệt...\" để thay đổi.",
            "reset": "Đặt lại",
            "start_idle": "\u00A0\u00A0Bắt đầu chia tệp",
            "start_preparing": "\u00A0\u00A0Đang chuẩn bị...",
            "start_converting": "\u00A0\u00A0Đang chuyển đổi...",
            "start_splitting": "\u00A0\u00A0Đang chia...",
            "start_cleaning": "\u00A0\u00A0Đang dọn...",
            "start_completed": "\u00A0\u00A0Hoàn tất",
            "start_error": "\u00A0\u00A0Lỗi",
            "open_output": "\u00A0\u00A0Mở thư mục đầu ra",
            "fileinfo_empty": "Chưa chọn tệp",
            "fileinfo_format": "Định dạng",
            "fileinfo_size": "Kích thước gốc",
            "fileinfo_duration": "Thời lượng",
            "fileinfo_chunks": "Số phần dự kiến",
            "size_warning_below_reliable": f"Dưới {min_reliable_chunk_size_mb} MB, một số tệp có thể thất bại.",
            "overlay_preparing_title": "Đang chuẩn bị",
            "overlay_preparing_body": "MediaSeg đang chuẩn bị tệp hiện tại. Các điều khiển tạm thời bị khóa.",
            "overlay_converting_title": "Đang chuyển đổi",
            "overlay_converting_body": "MediaSeg đang chuyển đổi tệp trước khi chia. Các điều khiển tạm thời bị khóa.",
            "overlay_splitting_title": "Đang chia",
            "overlay_splitting_body": "MediaSeg đang chia tệp hiện tại. Các điều khiển tạm thời bị khóa.",
            "overlay_cleaning_title": "Đang dọn",
            "overlay_cleaning_body": "MediaSeg đang dọn các tệp tạm. Các điều khiển tạm thời bị khóa.",
        },
    }


def system_language_code():
    locale_name = QLocale.system().name().lower()
    if locale_name.startswith("ja"):
        return LANG_JA
    if locale_name.startswith("vi"):
        return LANG_VI
    return LANG_EN
